services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.1.3
    container_name: keycloak-dev
    ports:
      - "8080:8080"
    environment:
      KC_DB: dev-file
      KC_HTTP_ENABLED: "true"
      KC_HEALTH_ENABLED: "true"
      KC_METRICS_ENABLED: "true"
      KC_FEATURES: scripts
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    command: ["start-dev"]
    restart: unless-stopped
