name: Deploy Keycloak

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Build Docker image
      run: docker build -t keycloak-app .
      
    - name: Deploy to production
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      run: |
        echo "Deploying to production..."
        # Adicione aqui seus comandos de deploy
        # docker push keycloak-app
        # kubectl apply -f k8s/ 